version: '3'

networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.23.0.0/16

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 172.23.0.7
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "85:80/tcp"
    #- "443:443/tcp"
    environment:
    - 'TZ=Europe/London'
    - 'WEBPASSWORD=password'
    - 'DNS1=172.23.0.7#5053'
    - 'DNS2=no'
    volumes:
    - '/home/ubuntu/docker/pihole/etc-pihole/:/etc/pihole/'
    - '/home/ubuntu/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      dns_net:
        ipv4_address: 172.23.0.8
    volumes:
    - /home/ubuntu/docker/unbound:/opt/unbound/etc/unbound
    ports:
    - "5053:53/tcp"
    - "5053:53/udp"
    restart: unless-stopped